In [2]:
# -*- coding:UTF-8 -*-
import datetime
import os

import pymysql
import pandas as pd
from sqlalchemy import create_engine




import pymssql 
import pymysql
import pandas as pd

def sync_station_data(now):
    # 表名
    station_table = "TAB_StationInfo"
    aws_table = "TAB_Aws2019"
    mws_table = "TAB_Mws2019"

    # 两站表名
    station_dict = {
        aws_table: {
            "station_type": 1,
            "criteria": ' st.Province = "浙江" ',
        },
        mws_table: {
            "station_type": 2,
            "criteria": ' st.Province = "浙江" and st.City = "台州" ',
        }
    }
    # 远程数据库
    remote_connector = pymysql.connect(
        host="127.0.0.1",
        port=3306,
        user="root",
        password="051219",
        db="ZJSZDZDB"
    )

    # 获取当前日期
    now = now
    one_day_delta = datetime.timedelta(days=1)
    date = now#now.date()
    start_time = (date - one_day_delta).strftime("%Y-%m-%d") + " 21:00:00"
    end_time = date.strftime("%Y-%m-%d") + " 20:59:59"
    if now.time().hour > 20:
        date = date + one_day_delta
        start_time = date.strftime("%Y-%m-%d") + " 21:00:00"
        end_time = (date + one_day_delta).strftime("%Y-%m-%d") + " 20:59:59"
    remote_connector.connect()
    # 执行sql
    datalist = []
    for table in station_dict.keys():
        # 查询气象站数据
        query = f"""
        select r1.IIiii as station_no,
        r1.Province as station_province,
        r1.City as station_city,
        r1.County as station_county,
        r1.Town as station_town,
        r1.Village as station_village,
        r1.Country as station_country,
        r1.station_name as station_name, 
        r1.lon as lon, r1.lat as lat,
        r1.rain as p_total, r1.tmax as t_max, r1.tmin as t_min, r2.wind_max as w_max, r2.wind_dir as w_dir, r1.vis as vis from
        (select st.IIiii as IIiii, 
        max(st.Province) as Province,
        max(st.City) as City,
        max(st.County) as County,
        max(st.Town) as Town,
        max(st.Village) as Village,
        max(st.Country) as Country,
        max(st.StationName) as station_name,  
        max(st.lon) as lon, max(st.lat) as lat, 
        sum(if(sd.RR>0,sd.RR,0)) as rain, 
        max(if(sd.T>-2730,sd.T,null)) as tmax, 
        min(if(sd.T>-2730,sd.T,null)) as tmin, 
        min(if(sd.VV>=0,sd.VV,null)) as vis from {station_table} as st
        left join {table} as sd on sd.IIiii = st.IIiii
        where 1 = 1 and {station_dict.get(table)["criteria"]} and sd.tTime between "{start_time}" and "{end_time}"
        group by st.IIiii) as r1
        inner join
        (select wind.IIiii as IIiii, max(if(wind.fFy>=0,wind.fFy,null)) as wind_max, max(if(dFy>=0,dFy,null)) as wind_dir from
        (select st.IIiii as IIiii, sd.fFy as fFy, max(dFy) as dFy from {station_table} as st
        left join {table} as sd on sd.IIiii = st.IIiii
        where 1 = 1 and {station_dict.get(table)["criteria"]} and sd.tTime between "{start_time}" and "{end_time}"
        group by st.IIiii, sd.fFy) as wind
        group by wind.IIiii) as r2 on r2.IIiii = r1.IIiii
        """
        df_location = pd.read_sql(query, con=remote_connector)
        df_location['datetime'] = now
        datalist.append(df_location)
    return datalist
    
month_list = [31,28,31,30,31,30,31,31,30,31,30,31]
engine =create_engine('mysql+pymysql://root:051219@127.0.0.1:3306/tzweb',encoding='utf-8')#database数据库名字，password用户密码
for index, value in enumerate(month_list):
    days = value
    month = index + 1
    if month==1:
        today = datetime.date.today()
        year = today.year
        all_data = []
        for i in range(days-1):
            now = datetime.date(2019, month, i+1).strftime("%Y-%m-%d %H:%M:%S")
            now = datetime.datetime.strptime(now, '%Y-%m-%d %H:%M:%S')
            data = sync_station_data(now)
            all_data = all_data + data
        station_all = pd.concat(all_data)
        station_all.to_sql('station_data',con=engine,if_exists='replace',index=False)#数据库中表名，
    else:
        today = datetime.date.today()
        year = today.year
        all_data = []
        for i in range(days-1):
            now = datetime.date(2019, month, i+1).strftime("%Y-%m-%d %H:%M:%S")
            now = datetime.datetime.strptime(now, '%Y-%m-%d %H:%M:%S')
            data = sync_station_data(now)
            all_data = all_data + data
        station_all = pd.concat(all_data)
        station_all.to_sql('station_data',con=engine,if_exists='append',index=False)#数据库中表名，
print("data is ok")        
            
# today = datetime.date.today()
# year = today.year
# month = today.month
# all_data = []
# for i in range(30):
#     now = datetime.date(2019, 5, i+1).strftime("%Y-%m-%d %H:%M:%S")
#     now = datetime.datetime.strptime(now, '%Y-%m-%d %H:%M:%S')
#     data = sync_station_data(now)
#     all_data = all_data + data
# station_all = pd.concat(all_data)

# engine =create_engine('mysql+pymysql://root:051219@127.0.0.1:3306/tzweb',encoding='utf-8')#database数据库名字，password用户密码
# station_all.to_sql('station_data',con=engine,if_exists='append',index=False)#数据库中表名，

NameError: name 'station_all' is not defined